version: '3.5'

services:

  # Site des adhérents de l'association
  sgpc:
    build: .
    container_name: sgpc
    hostname: sgpc
    stdin_open: true
    tty: true
    ports:
    - "80:80"
    - "3306:3306"
    volumes:
    - ./src/:/var/www/html
